[project]
name = "nppes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.30.0",
    "numpy>=2.3.2",
    "polars>=1.32.0",
    "pyinstaller>=6.14.2",
    "sv-ttk>=2.6.1",
]
